data:
  glob_pattern: "/media/lithiumice/MISC2/Public-Datasets/loco_dataset/bilibili_locomotion_up_id_396441315_tram_processed_difftraj_npzs_him_imitated/*.npz"
  output_folder: "/media/lithiumice/MISC2/Public-Datasets/loco_dataset/bilibili_locomotion_up_id_396441315_tram_processed_difftraj_npzs_him_imitated_pyvista_render"
  
process_params:
  # debug: true
  debug: false
  use_ray_cluster: false

model_paths:

model_params:

scaling_params:
  num_gpu_per_processor: 0.1
  CUDA_VISIBLE_DEVICES: 