data:
  glob_pattern: "/media/lithiumice/MISC2/2_Datasets/1_LOCO/2_bilibili_up396441315/2_him_imitated/*.npz"
  output_folder: "/media/lithiumice/MISC2/2_Datasets/1_LOCO/2_bilibili_up396441315/3_pyvista_render"
  
process_params:
  # debug: true
  debug: false
  use_ray_cluster: false

model_paths:

model_params:

scaling_params:
  num_gpu_per_processor: 0.1
  CUDA_VISIBLE_DEVICES: 